version: 2

project_name: mdtoc

env:
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy

gomod:
  proxy: true

builds:
  - id: mdtoc
    dir: .
    no_unique_dist_dir: true
    binary: mdtoc-{{ .Arch }}-{{ .Os }}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - '7'
    ignore:
      - goos: windows
        goarch: arm
    flags:
      - -trimpath
    ldflags:
      - "{{ .Env.LDFLAGS }}"

archives:
  - formats:
      - binary
    name_template: "{{ .Binary }}"
    allow_different_binary_count: true

signs:
  - id: mdtoc-keyless
    signature: "${artifact}.sigstore.json"
    cmd: cosign
    args:
      - sign-blob
      - --bundle=${signature}
      - --yes
      - ${artifact}
    artifacts: all

sboms:
  - artifacts: binary

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ .Tag }}-next"

release:
  github:
    owner: kubernetes-sigs
    name: mdtoc
  prerelease: auto

changelog:
  use: github-native
